package com.example.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import javax.persistence.*;

/**
 * This is a class that models an Account.
 *
 * You should NOT make any modifications to this class.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "account")
public class Account {
    /**
     * An id for this Account. You should use this as the Entity's ID.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer account_id;
    /**
     * A username for this Account (must be unique and not blank)
     */
    private String username;
    /**
     * A password for this account (must be over 4 characters)
     */
    private String password;
    /**
     * When posting a new Account, the id can be generated by the database. In that case, a constructor without
     * account_id is needed.
     * @param username
     * @param password
     */
    public Account(String username, String password){
        this.username = username;
        this.password = password;
    }
}